# Changes here will be overwritten by Copier
Authors: Joaquim Luis jluis@ualg.pt
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Joaquim Luis jluis@ualg.pt
PackageName: F3D
PackageOwner: joa-quim
PackageUUID: 9c67f86a-bae4-5246-a7f1-3af54b9e6640
StrategyConfirmIncluded: false
StrategyLevel: 1
StrategyReviewExcluded: true
_src_path: C:\Users\j\.julia\packages\BestieTemplate\53KEa
